### PR TITLE
support more activerecord and PostgreSQL versions

### PR DESCRIPTION
**Pull request by ashkulz**

### CODE REVIEW

**Review by urkle — CHANGES_REQUESTED** [review]
Do we need to update the gemspec to require activesupport, '>= 5.2', '< 6.2'
?

**Comment by ashkulz** [comment]
I wanted to do that after we actually verified that the tests pass on TravisCI, do you want me to do that beforehand?

**Comment by urkle** [comment]
might as well as it may cause dependency issues in the other gems

**Comment by ashkulz** [comment]
@urkle done, also pushed a change in the linked PR for `schema_plus_core`. I'll follow up with PRs for other gems once tests are green for it.

**Comment by ashkulz** [comment]
Anything more left to be done, @urkle?

**Review by urkle — APPROVED** [review]

**Comment by urkle** [comment]
@ashkulz ugh..  I'm going to have to create a new PR for this gem to switch OFF of travis and onto GH actions.. as travis CI is not fully "free" any longer.

**Comment by ashkulz** [comment]
I was wondering how TravisCI was running, tbh -- I guess the migration won't be easy/straightforward :see_no_evil:

**Comment by urkle** [comment]
@ashkulz apparently you can only run "free" on travisCI if you use ARM cpu machines.  and honestly I'm getting sick of constly having to redo the travis configs every few months when they break things.

I have an initial conversion to github actions in my schema_dev branch and am working on one for schema_monkey.  once I figure how to get it all working w/ schema monkey I'll "generalize" it in schema_dev.

**Comment by ronen** [comment]
@urkle, @ashkulz - great to see that SchemaPlus still has some life in it :) Thanks for working on it!

**Comment by urkle** [comment]
@ronen can we move the modware repo into the SchemaPlus organization?   I'd like to update that gem some.. (mainly get it tested on newer ruby versions as well as drop old ruby versions e.g. removing need for keystruct gem)

**Comment by ronen** [comment]
> @ronen can we move the modware repo into the SchemaPlus organization? I'd like to update that gem some.. (mainly get it tested on newer ruby versions as well as drop old ruby versions e.g. removing need for keystruct gem)

done!

**Comment by urkle** [comment]
@ronen thanks!.. also can you add me to the package on rubygems?

**Comment by ronen** [comment]
> @ronen thanks!.. also can you add me to the package on rubygems?

oh yeah, good point :)

also done!

**Pull request merged**
